server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.sprint.mission.discodeit: info
    org.hibernate.SQL: info

management:
  endpoint:
    health:
      show-details: never

  info:
    env:
      enabled: false